# Generated by Django 5.1.2 on 2025-02-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-created']},
        ),
    ]
